### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by kerrtravers** [Mountios/Mountio-database#4]
Are you really going to store user lists and data on an open-source repo?

**Comment by radioblahaj** [comment]
We don't have privte repos, :c

**Comment by kerrtravers** [comment]
Still, Is that not invasion of user privacy?

**Comment by radioblahaj** [comment]
Yes, but we need privte repos

**Comment by ktrvs** [comment]
Well if it is an invasion of user privacy, why are you keeping the data here instead of somewhere a lot more secure?

**Comment by radioblahaj** [comment]
What would we secure?
Plus, this is fake users.

**Comment by radioblahaj** [comment]
ktrvs
